// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fable.MaterialUI")>]
[<assembly: AssemblyProductAttribute("Fable.MaterialUI")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings for MaterialUI")>]
[<assembly: AssemblyVersionAttribute("1.3.2")>]
[<assembly: AssemblyFileVersionAttribute("1.3.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.MaterialUI"
    let [<Literal>] AssemblyProduct = "Fable.MaterialUI"
    let [<Literal>] AssemblyDescription = "Fable bindings for MaterialUI"
    let [<Literal>] AssemblyVersion = "1.3.2"
    let [<Literal>] AssemblyFileVersion = "1.3.2"
    let [<Literal>] AssemblyConfiguration = "Release"
