// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fable.MaterialUI")>]
[<assembly: AssemblyProductAttribute("Fable.MaterialUI")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings for MaterialUI")>]
[<assembly: AssemblyVersionAttribute("2.0.1")>]
[<assembly: AssemblyFileVersionAttribute("2.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.MaterialUI"
    let [<Literal>] AssemblyProduct = "Fable.MaterialUI"
    let [<Literal>] AssemblyDescription = "Fable bindings for MaterialUI"
    let [<Literal>] AssemblyVersion = "2.0.1"
    let [<Literal>] AssemblyFileVersion = "2.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
